### ISSUE TITLE
Not really an issue :)

### ISSUE THREAD

**Issue by poetaster** [shimpe/sc-lsystem#1]
Hi, I just wanted to let you know that someone is using your LSytems 

https://github.com/poetaster/supercollider-lsystems

gosper-2.scd is pretty good :) I'm not using your panola approach but pbind(ef) and it's all about some drawing I did last year. There's some info and examples (visual and the audio) https://poetaster.de/sc-ls/ 

Thanks for the great Quark.

**Comment by shimpe** [comment]
Thanks for trying it out and letting me know!

**Comment by poetaster** [comment]
Thanks for making sc-lsystems!
